<?php

if (stripos($value, '.com')) { $country = ""; }
elseif (stripos($value, 'co.uk')) { $country = "United Kingdom"; }
elseif (stripos($value, '.net')) { $country = ""; }
elseif (stripos($value, '.org')) { $country = ""; }
elseif (stripos($value, '.fm')) { $country = ""; }

elseif (stripos($value, '.af')){ $country = "Afghanistan"; }
elseif (stripos($value, '.ax')) { $country = "Aland Islands"; }
elseif (stripos($value, '.AL')) { $country = "Albania"; }
elseif (stripos($value, '.DZ')) { $country = "Algeria"; }
elseif (stripos($value, '.AS')) { $country = "American Samoa"; }
elseif (stripos($value, '.AD')) { $country = "Andorra"; }
elseif (stripos($value, '.AO')) { $country = "Angola"; }
elseif (stripos($value, '.AI')) { $country = "Anguilla"; }
elseif (stripos($value, '.AQ')) { $country = "Antarctica"; }
elseif (stripos($value, '.AG')) { $country = "Antigua & Barbuda"; }
elseif (stripos($value, '.AR')) { $country = "Argentina"; }
elseif (stripos($value, '.AM')) { $country = "Armenia"; }
elseif (stripos($value, '.AW')) { $country = "Aruba"; }
elseif (stripos($value, '.AU')) { $country = "Australia"; }
elseif (stripos($value, '.AT')) { $country = "Austria"; }
elseif (stripos($value, '.AZ')) { $country = "Azerbaijan"; }
elseif (stripos($value, '.BS')) { $country = "Bahamas"; }
elseif (stripos($value, '.BH')) { $country = "Bahrain"; }
elseif (stripos($value, '.BD')) { $country = "Bangladesh"; }
elseif (stripos($value, '.BB')) { $country = "Barbados"; }
elseif (stripos($value, '.BY')) { $country = "Belarus"; }
elseif (stripos($value, '.BE')) { $country = "Belgium"; }
elseif (stripos($value, '.BZ')) { $country = "Belize"; }
elseif (stripos($value, '.BJ')) { $country = "Benin"; }
elseif (stripos($value, '.BM')) { $country = "Bermuda"; }
elseif (stripos($value, '.BT')) { $country = "Bhutan"; }
elseif (stripos($value, '.BO')) { $country = "Bolivia"; }
elseif (stripos($value, '.BQ')) { $country = "Bonaire, Saint Eustatius & Saba"; }
elseif (stripos($value, '.BA')) { $country = "Bosnia & Herzegovina"; }
elseif (stripos($value, '.BW')) { $country = "Botswana"; }
elseif (stripos($value, '.BV')) { $country = "Bouvet Island"; }
elseif (stripos($value, '.BR')) { $country = "Brazil"; }
elseif (stripos($value, '.IO')) { $country = "British Indian Ocean Territory"; }
elseif (stripos($value, '.VG')) { $country = "British Virgin Islands"; }
elseif (stripos($value, '.BN')) { $country = "Brunei"; }
elseif (stripos($value, '.BG')) { $country = "Bulgaria"; }
elseif (stripos($value, '.BF')) { $country = "Burkina Faso"; }
elseif (stripos($value, '.BI')) { $country = "Burundi"; }
elseif (stripos($value, '.KH')) { $country = "Cambodia"; }
elseif (stripos($value, '.CM')) { $country = "Cameroon"; }
elseif (stripos($value, '.CA')) { $country = "Canada"; }
elseif (stripos($value, '.CV')) { $country = "Cape Verde"; }
elseif (stripos($value, '.KY')) { $country = "Cayman Islands"; }
elseif (stripos($value, '.CF')) { $country = "Central African Republic"; }
elseif (stripos($value, '.TD')) { $country = "Chad"; }
elseif (stripos($value, '.CL')) { $country = "Chile"; }
elseif (stripos($value, '.CN')) { $country = "China"; }
elseif (stripos($value, '.CX')) { $country = "Christmas Island"; }
elseif (stripos($value, '.CC')) { $country = "Cocos Islands"; }
elseif (stripos($value, '.CO')) { $country = "Colombia"; }
elseif (stripos($value, '.KM')) { $country = "Comoros"; }
elseif (stripos($value, '.CK')) { $country = "Cook Islands"; }
elseif (stripos($value, '.CR')) { $country = "Costa Rica"; }
elseif (stripos($value, '.HR')) { $country = "Croatia"; }
elseif (stripos($value, '.CU')) { $country = "Cuba"; }
elseif (stripos($value, '.CW')) { $country = "Curacao"; }
elseif (stripos($value, '.CY')) { $country = "Cyprus"; }
elseif (stripos($value, '.CZ')) { $country = "Czech Republic"; }
elseif (stripos($value, '.CD')) { $country = "Democratic Republic of the Congo"; }
elseif (stripos($value, '.DK')) { $country = "Denmark"; }
elseif (stripos($value, '.DJ')) { $country = "Djibouti"; }
elseif (stripos($value, '.DM')) { $country = "Dominica"; }
elseif (stripos($value, '.DO')) { $country = "Dominican Republic"; }
elseif (stripos($value, '.TL')) { $country = "East Timor"; }
elseif (stripos($value, '.EC')) { $country = "Ecuador"; }
elseif (stripos($value, '.EG')) { $country = "Egypt"; }
elseif (stripos($value, '.SV')) { $country = "El Salvador"; }
elseif (stripos($value, '.GQ')) { $country = "Equatorial Guinea"; }
elseif (stripos($value, '.ER')) { $country = "Eritrea"; }
elseif (stripos($value, '.EE')) { $country = "Estonia"; }
elseif (stripos($value, '.ET')) { $country = "Ethiopia"; }
elseif (stripos($value, '.FK')) { $country = "Falkland Islands"; }
elseif (stripos($value, '.FO')) { $country = "Faroe Islands"; }
elseif (stripos($value, '.FJ')) { $country = "Fiji"; }
elseif (stripos($value, '.FI')) { $country = "Finland"; }
elseif (stripos($value, '.FR')) { $country = "France"; }
elseif (stripos($value, '.GF')) { $country = "French Guiana"; }
elseif (stripos($value, '.PF')) { $country = "French Polynesia"; }
elseif (stripos($value, '.TF')) { $country = "French Southern Territories"; }
elseif (stripos($value, '.GA')) { $country = "Gabon"; }
elseif (stripos($value, '.GM')) { $country = "Gambia"; }
elseif (stripos($value, '.GE')) { $country = "Georgia"; }
elseif (stripos($value, '.DE')) { $country = "Germany"; }
elseif (stripos($value, '.GH')) { $country = "Ghana"; }
elseif (stripos($value, '.GI')) { $country = "Gibraltar"; }
elseif (stripos($value, '.GR')) { $country = "Greece"; }
elseif (stripos($value, '.GL')) { $country = "Greenland"; }
elseif (stripos($value, '.GD')) { $country = "Grenada"; }
elseif (stripos($value, '.GP')) { $country = "Guadeloupe"; }
elseif (stripos($value, '.GU')) { $country = "Guam"; }
elseif (stripos($value, '.GT')) { $country = "Guatemala"; }
elseif (stripos($value, '.GG')) { $country = "Guernsey"; }
elseif (stripos($value, '.GN')) { $country = "Guinea"; }
elseif (stripos($value, '.GW')) { $country = "Guinea-Bissau"; }
elseif (stripos($value, '.GY')) { $country = "Guyana"; }
elseif (stripos($value, '.HT')) { $country = "Haiti"; }
elseif (stripos($value, '.HM')) { $country = "Heard Island & McDonald Islands"; }
elseif (stripos($value, '.HN')) { $country = "Honduras"; }
elseif (stripos($value, '.HK')) { $country = "Hong Kong"; }
elseif (stripos($value, '.HU')) { $country = "Hungary"; }
elseif (stripos($value, '.IS')) { $country = "Iceland"; }
elseif (stripos($value, '.IN')) { $country = "India"; }
elseif (stripos($value, '.ID')) { $country = "Indonesia"; }
elseif (stripos($value, '.IR')) { $country = "Iran"; }
elseif (stripos($value, '.IQ')) { $country = "Iraq"; }
elseif (stripos($value, '.IE')) { $country = "Ireland"; }
elseif (stripos($value, '.IM')) { $country = "Isle of Man"; }
elseif (stripos($value, '.IL')) { $country = "Israel"; }
elseif (stripos($value, '.IT')) { $country = "Italy"; }
elseif (stripos($value, '.CI')) { $country = "Ivory Coast"; }
elseif (stripos($value, '.JM')) { $country = "Jamaica"; }
elseif (stripos($value, '.JP')) { $country = "Japan"; }
elseif (stripos($value, '.JE')) { $country = "Jersey"; }
elseif (stripos($value, '.JO')) { $country = "Jordan"; }
elseif (stripos($value, '.KZ')) { $country = "Kazakhstan"; }
elseif (stripos($value, '.KE')) { $country = "Kenya"; }
elseif (stripos($value, '.KI')) { $country = "Kiribati"; }
elseif (stripos($value, '.XK')) { $country = "Kosovo"; }
elseif (stripos($value, '.KW')) { $country = "Kuwait"; }
elseif (stripos($value, '.KG')) { $country = "Kyrgyzstan"; }
elseif (stripos($value, '.LA')) { $country = "Laos"; }
elseif (stripos($value, '.LV')) { $country = "Latvia"; }
elseif (stripos($value, '.LB')) { $country = "Lebanon"; }
elseif (stripos($value, '.LS')) { $country = "Lesotho"; }
elseif (stripos($value, '.LR')) { $country = "Liberia"; }
elseif (stripos($value, '.LY')) { $country = "Libya"; }
elseif (stripos($value, '.LI')) { $country = "Liechtenstein"; }
elseif (stripos($value, '.LT')) { $country = "Lithuania"; }
elseif (stripos($value, '.LU')) { $country = "Luxembourg"; }
elseif (stripos($value, '.MO')) { $country = "Macao"; }
elseif (stripos($value, '.MK')) { $country = "FYROM"; }
elseif (stripos($value, '.MG')) { $country = "Madagascar"; }
elseif (stripos($value, '.MW')) { $country = "Malawi"; }
elseif (stripos($value, '.MY')) { $country = "Malaysia"; }
elseif (stripos($value, '.MV')) { $country = "Maldives"; }
elseif (stripos($value, '.ML')) { $country = "Mali"; }
elseif (stripos($value, '.MT')) { $country = "Malta"; }
elseif (stripos($value, '.MH')) { $country = "Marshall Islands"; }
elseif (stripos($value, '.MQ')) { $country = "Martinique"; }
elseif (stripos($value, '.MR')) { $country = "Mauritania"; }
elseif (stripos($value, '.MU')) { $country = "Mauritius"; }
elseif (stripos($value, '.YT')) { $country = "Mayotte"; }
elseif (stripos($value, '.MX')) { $country = "Mexico"; }
elseif (stripos($value, '.FM')) { $country = "Micronesia"; }
elseif (stripos($value, '.MD')) { $country = "Moldova"; }
elseif (stripos($value, '.MC')) { $country = "Monaco"; }
elseif (stripos($value, '.MN')) { $country = "Mongolia"; }
elseif (stripos($value, '.ME')) { $country = "Montenegro"; }
elseif (stripos($value, '.MS')) { $country = "Montserrat"; }
elseif (stripos($value, '.MA')) { $country = "Morocco"; }
elseif (stripos($value, '.MZ')) { $country = "Mozambique"; }
elseif (stripos($value, '.MM')) { $country = "Myanmar"; }
elseif (stripos($value, '.NA')) { $country = "Namibia"; }
elseif (stripos($value, '.NR')) { $country = "Nauru"; }
elseif (stripos($value, '.NP')) { $country = "Nepal"; }
elseif (stripos($value, '.NL')) { $country = "Netherlands"; }
elseif (stripos($value, '.AN')) { $country = "Netherlands Antilles"; }
elseif (stripos($value, '.NC')) { $country = "New Caledonia"; }
elseif (stripos($value, '.NZ')) { $country = "New Zealand"; }
elseif (stripos($value, '.NI')) { $country = "Nicaragua"; }
elseif (stripos($value, '.NE')) { $country = "Niger"; }
elseif (stripos($value, '.NG')) { $country = "Nigeria"; }
elseif (stripos($value, '.NU')) { $country = "Niue"; }
elseif (stripos($value, '.NF')) { $country = "Norfolk Island"; }
elseif (stripos($value, '.KP')) { $country = "North Korea"; }
elseif (stripos($value, '.MP')) { $country = "Northern Mariana Islands"; }
elseif (stripos($value, '.NO')) { $country = "Norway"; }
elseif (stripos($value, '.OM')) { $country = "Oman"; }
elseif (stripos($value, '.PK')) { $country = "Pakistan"; }
elseif (stripos($value, '.PW')) { $country = "Palau"; }
elseif (stripos($value, '.PS')) { $country = "Palestinian Territory"; }
elseif (stripos($value, '.PA')) { $country = "Panama"; }
elseif (stripos($value, '.PG')) { $country = "Papua New Guinea"; }
elseif (stripos($value, '.PY')) { $country = "Paraguay"; }
elseif (stripos($value, '.PE')) { $country = "Peru"; }
elseif (stripos($value, '.PH')) { $country = "Philippines"; }
elseif (stripos($value, '.PN')) { $country = "Pitcairn"; }
elseif (stripos($value, '.PL')) { $country = "Poland"; }
elseif (stripos($value, '.PT')) { $country = "Portugal"; }
elseif (stripos($value, '.PR')) { $country = "Puerto Rico"; }
elseif (stripos($value, '.QA')) { $country = "Qatar"; }
elseif (stripos($value, '.CG')) { $country = "Republic of the Congo"; }
elseif (stripos($value, '.RE')) { $country = "Reunion"; }
elseif (stripos($value, '.RO')) { $country = "Romania"; }
elseif (stripos($value, '.RU')) { $country = "Russia"; }
elseif (stripos($value, '.RW')) { $country = "Rwanda"; }
elseif (stripos($value, '.BL')) { $country = "Saint Barthelemy"; }
elseif (stripos($value, '.SH')) { $country = "Saint Helena"; }
elseif (stripos($value, '.KN')) { $country = "Saint Kitts & Nevis"; }
elseif (stripos($value, '.LC')) { $country = "Saint Lucia"; }
elseif (stripos($value, '.MF')) { $country = "Saint Martin"; }
elseif (stripos($value, '.PM')) { $country = "Saint Pierre & Miquelon"; }
elseif (stripos($value, '.VC')) { $country = "Saint Vincent & the Grenadines"; }
elseif (stripos($value, '.WS')) { $country = "Samoa"; }
elseif (stripos($value, '.SM')) { $country = "San Marino"; }
elseif (stripos($value, '.ST')) { $country = "Sao Tome & Principe"; }
elseif (stripos($value, '.SA')) { $country = "Saudi Arabia"; }
elseif (stripos($value, '.SN')) { $country = "Senegal"; }
elseif (stripos($value, '.RS')) { $country = "Serbia"; }
elseif (stripos($value, '.CS')) { $country = "Serbia & Montenegro"; }
elseif (stripos($value, '.SC')) { $country = "Seychelles"; }
elseif (stripos($value, '.SL')) { $country = "Sierra Leone"; }
elseif (stripos($value, '.SG')) { $country = "Singapore"; }
elseif (stripos($value, '.SX')) { $country = "Sint Maarten"; }
elseif (stripos($value, '.SK')) { $country = "Slovakia"; }
elseif (stripos($value, '.SI')) { $country = "Slovenia"; }
elseif (stripos($value, '.SB')) { $country = "Solomon Islands"; }
elseif (stripos($value, '.SO')) { $country = "Somalia"; }
elseif (stripos($value, '.ZA')) { $country = "South Africa"; }
elseif (stripos($value, '.GS')) { $country = "South Georgia & the South Sandwich Islands"; }
elseif (stripos($value, '.KR')) { $country = "South Korea"; }
elseif (stripos($value, '.SS')) { $country = "South Sudan"; }
elseif (stripos($value, '.ES')) { $country = "Spain"; }
elseif (stripos($value, '.LK')) { $country = "Sri Lanka"; }
elseif (stripos($value, '.SD')) { $country = "Sudan"; }
elseif (stripos($value, '.SR')) { $country = "Suriname"; }
elseif (stripos($value, '.SJ')) { $country = "Svalbard & Jan Mayen"; }
elseif (stripos($value, '.SZ')) { $country = "Swaziland"; }
elseif (stripos($value, '.SE')) { $country = "Sweden"; }
elseif (stripos($value, '.CH')) { $country = "Switzerland"; }
elseif (stripos($value, '.SY')) { $country = "Syria"; }
elseif (stripos($value, '.TW')) { $country = "Taiwan"; }
elseif (stripos($value, '.TJ')) { $country = "Tajikistan"; }
elseif (stripos($value, '.TZ')) { $country = "Tanzania"; }
elseif (stripos($value, '.TH')) { $country = "Thailand"; }
elseif (stripos($value, '.TG')) { $country = "Togo"; }
elseif (stripos($value, '.TK')) { $country = "Tokelau"; }
elseif (stripos($value, '.TO')) { $country = "Tonga"; }
elseif (stripos($value, '.TT')) { $country = "Trinidad & Tobago"; }
elseif (stripos($value, '.TN')) { $country = "Tunisia"; }
elseif (stripos($value, '.TR')) { $country = "Turkey"; }
elseif (stripos($value, '.TM')) { $country = "Turkmenistan"; }
elseif (stripos($value, '.TC')) { $country = "Turks & Caicos Islands"; }
elseif (stripos($value, '.TV')) { $country = "Tuvalu"; }
elseif (stripos($value, '.VI')) { $country = "U.S. Virgin Islands"; }
elseif (stripos($value, '.UG')) { $country = "Uganda"; }
elseif (stripos($value, '.UA')) { $country = "Ukraine"; }
elseif (stripos($value, '.AE')) { $country = "United Arab Emirates"; }
elseif (stripos($value, '.GB')) { $country = "United Kingdom"; }
elseif (stripos($value, '.US')) { $country = "United States"; }
elseif (stripos($value, '.UM')) { $country = "United States Minor Outlying Islands"; }
elseif (stripos($value, '.UY')) { $country = "Uruguay"; }
elseif (stripos($value, '.UZ')) { $country = "Uzbekistan"; }
elseif (stripos($value, '.VU')) { $country = "Vanuatu"; }
elseif (stripos($value, '.VA')) { $country = "Vatican"; }
elseif (stripos($value, '.VE')) { $country = "Venezuela"; }
elseif (stripos($value, '.VN')) { $country = "Vietnam"; }
elseif (stripos($value, '.WF')) { $country = "Wallis & Futuna"; }
elseif (stripos($value, '.EH')) { $country = "Western Sahara"; }
elseif (stripos($value, '.YE')) { $country = "Yemen"; }
elseif (stripos($value, '.ZM')) { $country = "Zambia"; }
elseif (stripos($value, '.ZW')) { $country = "Zimbabwe"; }

else { $country == ""; }

?>